#!/usr/bin/env bash
# convert 1-column list with 2-column-categorised
# category name should be started with '#'
awk -F# 'BEGIN {OFS="\t"; print "Category\tUniqName"} {if ($2!="") {categ = $2} else {print categ,$1}}'
