#!/usr/bin/env bash
# to download from wiki and then parce to csv list of russian federal subjects
# english version
curl -s https://en.wikipedia.org/wiki/Federal_subjects_of_Russia | sed -n '/wikitable sortable/,/\/table/p' | tr -d '\n|,' | sed -r 's/<tr[^>]*>/\n/g; s/<t[dh][^>]*>/,/g; s/<[^>]+>|&#160;|\[[a-zA-Z0-9]+\]//g' | awk -F, '$2!~/^$/ {print}' | sed -n '/^,Code/,/^,92/p'
